services:
  chaosstandard:
    build:
      context: .
      args:
        VITE_APP_HOST: "chaosstandard.ashhuston.com"

    container_name: chaosStandard
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carchaosstandarddviewer.rule=Host(`chaosstandard.ashhuston.com`)"
      - "traefik.http.routers.chaosstandard.entrypoints=websecure"
      - "traefik.http.routers.chaosstandard.tls.certresolver=letsencrypt"

      - "traefik.http.services.chaosstandard.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
